# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs


name: Altirev-Machine

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Nest.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: ‘yarn’

      - name: Install dependencies
        run: yarn

      - name: Build the project
        run: yarn build

      - name: Stop current PM2 process by name
        run: pm2 stop altirev || true

      - name: Start new PM2 process with name
        run: pm2 start dist/main.js — name altirev

      - name: Save PM2 process list
        run: pm2 save

